name: Auto Commit Files

on:
  push:
    paths:
      - 'files/**'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit New Files
        run: |
          git config user.name "AutoBot"
          git config user.email "bot@example.com"
          git add files/
          git commit -m "Auto commit new/updated files" || echo "Nothing to commit"
          git push
