name: Auto-Publish Staged Files

on:
  workflow_dispatch:
  push:
    paths:
      - 'staging/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SECRET_TOKEN }}

      - name: Prepare folders
        run: mkdir -p files

      - name: Move staged files to files folder
        run: |
          if compgen -G "staging/*.json" > /dev/null; then
            mv staging/*.json files/
          else
            echo "No files to publish."
          fi

      - name: Commit & Push new files
        run: |
          git config user.name "ClassifiedBot"
          git config user.email "classified-bot@example.com"
          git add files/
          git commit -m "📁 Auto-publish new file(s)" || echo "Nothing to commit"
          git push
